const mongoose = require('mongoose')

// Schema Setup
const mriSchema = new mongoose.Schema({
	division: String,
	month: String,
	short_months: String,
	extra_short_months: String,
	dealer_short_months: String,
	doa_dpu: Number,
	doa_rft_percent: Number,
	doa_machines: Number,
	t0_dpu: Number,
	t0_rft: Number,
	t0_machines: Number,
	t1_dpu: Number,
	t1_rft: Number,
	t1_machines: Number,
	t3_dpu: Number,
	t3_rft: Number,
	t3_rft_target: Number,
	t3_machines: Number,
	t6_dpu: Number,
	t6_rft: Number,
	t6_machines: Number,
	doa_dpu_target: Number,
	doa_rft_target: Number,
	t0_dpu_target: Number,
	t0_rft_target: Number,
	escape_dpu: Number,
	escape_dpu_target: Number,
	top10_dealer_rft: Number,
	top10_customer_rft: Number,
	major_escape_repeats: Number,
	doa_top50_repeat_percent: String,
	t0_top50_repeat_percent: String,
	top10_dealer_rft_target: Number,
	top10_customer_rft_target: Number,
	doa_4c_coverage_percent: Number,
	t0_4c_coverage_percent: Number,
	doa_top50_red: Number,
	doa_top50_amber: Number,
	doa_top50_green: Number,
	t0_top50_red: Number,
	t0_top50_amber: Number,
	t0_top50_green: Number,
	t3_machines: Number,
	t3_claims: Number,
	t3_top50_red: Number,
	t3_top50_amber: Number,
	t3_top50_green: Number,
	t3_top50_repeat_percent: String,
	t1_leaks_dpu: Number,
	t3_leaks_dpu: Number,
	t1_leaks_dpu_target: Number,
	t3_leaks_dpu_traget: Number,
	service_top10_operations_late: Number,
	service_top10_operations_total: Number,
	service_top10_supplier_late: Number,
	service_top10_supplier_total: Number,
	t3_operations_rft: Number,
	t3_operations_dpu: Number,
	t3_supplier_rft: Number,
	t3_supplier_dpu: Number,
	t3_design_rft: Number,
	t3_design_dpu: Number,
	t3_operations_rft_target: Number,
	t3_operations_dpu_target: Number,
	t3_supplier_rft_target: Number,
	t3_supplier_dpu_target: Number,
	t3_design_rft_target: Number,
	t3_design_dpu_target: Number,

	// people          : [
	// 	{
	// 		name      : {
	// 			type      : String,
	// 			unique    : true,
	// 			required  : [ true, 'Name is required' ],
	// 			trim      : true,
	// 			minLength : [ 2, 'Name must be longer than 2 characters' ],
	// 			maxLength : [ 100, 'Name name cannot exceed 100 characters' ],
	// 		},
	// 		dob       : {
	// 			type     : Date,
	// 			required : [ true, 'Date of birth is required' ],
	// 			trim     : true,
	// 		},
	// 		address   : {
	// 			number : Number,
	// 			street : String,
	// 			town   : String,
	// 			city   : String,
	// 			owner  : Boolean,
	// 		},
	// 		houseType : {
	// 			type     : String,
	// 			required : [ true, 'House type required' ],
	// 			enum     : {
	// 				values  : [ 'Detatched', 'Semi- detatched', 'Bungalo' ],
	// 				message : 'Please select correct house type from the list given',
	// 			},
	// 		},
	// 	},
	// ],
})

module.exports = mongoose.model('Mri', mriSchema)
