const mongoose = require('mongoose')

// Schema Setup
const qmrSchema = new mongoose.Schema(
	{
		division: String,
		name: String,
		impact: String,
		type: String,
		issues: String,
		process: String,
		visit: String,
		status: String,
		updatedBy: String,
		who: String,
		when: String,
		contribution: String,
		dpu_dec_21: String,
		dpu_current: String,
		closed_top_5: String,
		open_top_5: String,
		qty_joins: String,
		t3_impact: String,
		intro_date: String,
		comments: String,
		stat1: Number,
		stat2: Number,
		stat3: Number,
		stat4: Number,
		stat5: Number,
		stat6: Number,
		stat7: Number,
		stat8: Number,
		stat9: Number,
		stat10: Number,
		stat11: Number,
		stat12: Number,
		stat13: Number,
		target1: Number,
		target2: Number,
		target3: Number,
		target4: Number,
		target5: Number,
		target6: Number,
		target7: Number,
		target8: Number,
		target9: Number,
		target10: Number,
		target11: Number,
		target12: Number,
		target13: Number,
	},
	{ timestamps: true }
)

module.exports = mongoose.model('Qmr', qmrSchema)
